.github/workflows/deploy.yml, website/docusaurus.config.js
- Добавил Algolia поиск (локально не удается потестить. но на проде должно завестись)
- \+ Закинул токен в secrets
- Поправил редиректы
> Хотел еще пару моментов добавить из бэклога нашего - но пока времени мало
=> Добавил AlgoliaSearch, поправил редиректы

website/docusaurus.config.js
Нам пока активно бы собирать список компаний для продвижения и доклада
Думаю, если недельку повисит такой баннер, то особо от этого не потеряем
=> Добавил временно призыв добавить компании

website/src/app/index.css, website/src/features/header/ui.jsx
- Переопределил переменную, которая отвечает за цвет текста кнопок
- Удалил не используемый класс `text--secondary` у кнопки на главной, так как он перекрывается сейчас стилями самой кнопки
Close #261
=> Fix button color on home page

website/src/app/index.css
- Added by  @Mihir50
- Corrected css styles for firefox scrollbar
#315
=> WEBSITE-315: Fix css styles for scrollbar firefox

website/src/theme/Root.js
- **chore:** Временно скрыл наш виджет фидбека, чтобы не конфликтовал с HotJar-овским (см. скрин)
- Сам виджет настрою внутри HotJar, результаты "эксперимента" подведу по #325 через неделю
=> FEEDBACK-312: Remove self-made feedback widget usage (temporary)

website/i18n/en/docusaurus-plugin-content-docs/current/reference/layers/entities.md
- Добавил(а) ...
- Поправил(а) ...
=> Fix: import name in en

website/i18n/en/docusaurus-plugin-content-docs/current/concepts/index.mdx
- Ревью английского перевод `concepts/index` и правки
=> EDITING: Fix concepts translation

website/i18n/en/docusaurus-plugin-content-docs/current/concepts/low-coupling.md
- Поправил английский перевод `concepts/low-coupling`
=> EDITING: concepts/low-coupling translation

.github/pull_request_template.md, CONTRIBUTING.md
- Перевел CONTRIBUTING гайдлайны на англ
- Перевел PR-template на англ и актуализировал
=> CONTRIB-234-392: Translate guidelines

website/src/entities/example/index.jsx, website/src/shared/ui/row/index.jsx
PR возник из вопроса "А проект-пример XXX вообще смотрят?"
Но кажется после этого и на общую популярность и "запросы" можно будет смотреть
=> FEEDBACK: Setup GA for ExampleCard

.github/pull_request_template.md, CONTRIBUTING.md
- Edited PR template translation
- Edited CONTRIBUTING.md translation
See #416
=> Edit PR template and conributing guidelines translation

website/i18n/ru/docusaurus-plugin-content-docs/current/get-started/quick-start.md
Fixed the typo in quick-start.md
=> EDITING: (EN) Fix typo in quick-start

docusaurus.config.js, src/app/index.scss
=> chore: add no-war banner

package.json, src/entities/example/index.jsx, src/entities/example/styles.module.scss, src/pages/examples/_config.js
=> EXAMPLES: Add tech-list for example-cards (WIP)

blog/2022-06-04-rebranding.md, docusaurus.config.js, src/app/index.scss
=> BRAND: [BREAKING]! Set announce at blog (part 2/3)

i18n/en/docusaurus-plugin-content-docs/current/about/alternatives/atomic-design.mdx
Corrects "frament" to "fragment". Just found this randomly.
=> Fix a typo in the word "fragment"

i18n/en/code.json
Was about to get to the Intro page, but decided to look at the landing page first and couldn't hold myself back. 
1. Corrected a few translations to make them sound more natural (or in some cases, more understandable)
2. Changed "methodology" to "FSD" in the bottom text about companies. It was either that or add "this" before the word, otherwise it didn't sit right with me
=> fix(landing): Correct phrasing on the landing page

i18n/en/docusaurus-plugin-content-docs/current/guides/examples/auth.mdx
=> fix: "erikras" instead of "erikra"

i18n/en/docusaurus-plugin-content-docs/current/reference/units/layers/widgets.md, i18n/ru/docusaurus-plugin-content-docs/current/reference/units/layers/widgets.md
Add Navigation feature used in line 48, but not imported.
=> Add used import at documentation/widgets.md

i18n/en/docusaurus-plugin-content-docs/current/reference/isolation/index.md
Add english link to wikipedia article about GRASP (object-oriented design), because there is only russian version linked.
=> Add english link documentation/index.md

i18n/en/docusaurus-plugin-content-docs/current/get-started/tutorial.md, i18n/ru/docusaurus-plugin-content-docs/current/get-started/tutorial.md
* Add used imports combine, createEvent and createStore from effector.
* Add final semicolon to export.
* Add changes to english and russian file.
=> Add used imports documentation/tutorial.md

i18n/en/docusaurus-plugin-content-docs/current/reference/units/index.md
The current definition is an absolute nonsense 😬
I came up with a better explanation.
=> Fix `Segment` definition

i18n/en/docusaurus-plugin-content-docs/current/get-started/overview.md
1. When the first page that the user sees (consciously, https://feature-sliced.design/docs doesn't count) tells them if _it_ is right for them without telling them what the _it_ is, it feels like an out-of-context read
2. Putting the `api` in entities when you're using TanStack Query is the best thing ever, prove me wrong
3. The last advantage was phrased weird grammatically
Well, fix all of that
=> Fix the overview to read better

src/pages/examples/index.tsx
Old link didn't work
Replaced outdated link to actual
=> fix: add example url

i18n/en/docusaurus-plugin-content-docs/current/reference/index.mdx, i18n/ru/docusaurus-plugin-content-docs/current/reference/index.mdx
=> fix(reference): bug in links to slices-segments

config/docusaurus/routes.js
https://github.com/feature-sliced/documentation/pull/547/files
1. Add redirects from deleted pages to new pages
=> Add redirects to deleted pages

i18n/uz/code.json, i18n/uz/docusaurus-theme-classic/footer.json
Some translations viewed not right
Fixing some translates to uzb lang
=> wontfix: fixed some translations to uzb lang

i18n/en/docusaurus-plugin-content-docs/current/get-started/overview.md
Fix sentence inside overview.md
Before:
After:
=> docs: Update sentence in overview.md

package.json, pnpm-lock.yaml
Closes #566 
Update docusaurus from 2.1.0 to 2.4.1
=> chore: update docusaurus

.github/workflows/deploy.yml, .github/workflows/testing.yml, docusaurus.config.js, i18n/ru/docusaurus-plugin-content-docs/current/guides/examples/auth.mdx, package.json, pnpm-lock.yaml
1. Fix the typings of the Docusaurus config
2. Add a missing import for a component
3. Cache Docusaurus builds to speed up CI
=> fix: fix misc issues

package.json, pnpm-lock.yaml, src/app/index.scss, src/app/theme.scss, src/pages/examples/_config.ts, src/pages/index.tsx
For a long time I really didn't like reading our docs, and now I think I've found the reason — the Ubuntu font. It's just not readable for me.
I know we have a design language in Figma (which we ourselves don't even use in the mockups btw) which prescribes Overpass and IBM Plex Sans, but I tried it and wasn't happy with the result. IBM Plex Sans looks much too small, it doesn't help readability either. 
And here's when I got inspired by the approach of Starlight:
> By default, Starlight uses sans-serif fonts available on a user’s local device for all text. This ensures documentation loads quickly in a font that is familiar to each user, without requiring extra bandwidth to download large font files.
>
> https://starlight.astro.build/guides/customization/#custom-fonts
I like how it looks …
=> feat: remove custom fonts

i18n/en/docusaurus-plugin-content-docs/current/get-started/tutorial.md
Rephrased a sentence in a more natural way
=> Rephrase  

i18n/en/docusaurus-plugin-content-docs/current/guides/tech/with-nuxtjs.mdx, i18n/ru/docusaurus-plugin-content-docs/current/guides/tech/with-nuxtjs.mdx
Поправил файловый роутинг примера для большей очевидности (в en и ru версиях)
=> Статья "Использование в NuxtJs": Поправлен файловый роутинг примера

.github/workflows/deploy.yml, .github/workflows/testing.yml, package.json, pnpm-lock.yaml
=> fix: upgrade actions on CI

config/docusaurus/metadata.js, static/robots.txt
Our SEO sucks, we're not even indexed by Google
1. Add a robots.txt file
2. Add some tags to our website
=> feat: add a robots.txt file

i18n/kr/docusaurus-plugin-content-docs/current/guides/tech/with-react-query.mdx
We translated the Using with with-react-query page.
=> docs: with-react-query page translated into Korean

i18n/en/docusaurus-plugin-content-docs/current/guides/tech/with-react-query.mdx, i18n/ja/docusaurus-plugin-content-docs/current/guides/tech/with-react-query.mdx, i18n/kr/docusaurus-plugin-content-docs/current/guides/tech/with-react-query.mdx, i18n/ru/docusaurus-plugin-content-docs/current/guides/tech/with-react-query.mdx
=> fix: replace the leftover "experimental"-ness of `@x`

i18n/en/docusaurus-plugin-content-docs/current/reference/layers.mdx
Fix typo in layers.mdx
Fixed typo in layers.mdx
=> Fix typo in layers.mdx

i18n/en/docusaurus-plugin-content-docs/current/reference/public-api.md
=> fix: remove duplication of the word "accidentally"

i18n/kr/code.json
=> docs: code.json korean update

src/pages/examples/_config.ts
Edit Examples, example "conduit" use webpack
=> Edit Examples, example "conduit" use webpack

i18n/kr/docusaurus-plugin-content-docs/current/guides/tech/with-electron.mdx, i18n/kr/docusaurus-plugin-content-docs/current/guides/tech/with-nextjs.mdx, i18n/kr/docusaurus-plugin-content-docs/current/guides/tech/with-nuxtjs.mdx, i18n/kr/docusaurus-plugin-content-docs/current/guides/tech/with-react-query.mdx, i18n/kr/docusaurus-plugin-content-docs/current/guides/tech/with-sveltekit.mdx
The existing guide adequately covered the features, but I refined it with clearer phrasing and a consistent structure so that readers unfamiliar with FSD can grasp the flow at a glance.
=> docs(ko): refine tech-guide for improved readability

.github/workflows/build-preview.yml, .github/workflows/deploy-preview.yml, .github/workflows/deploy.yml, .github/workflows/testing.yml
The original Cloudflare GitHub app doesn't support preview deployments from forks. Here's a community-built alternative: https://github.com/AdrianGonz97/refined-cf-pages-action 
1. Set up "Refined CF Pages" for PR previews
2. Update the cache folders from webpack to rspack
=> chore: set up proper PR previews with Cloudflare

.github/workflows/build-preview.yml, .github/workflows/deploy-preview.yml, docusaurus.config.js
=> fix: base URL in PR previews
