website/src/pages/index.jsx

Кажется оригинальное предложение звучит как призыв стать частью большого сообщества и получить профиты основываясь на имени feature-sliced, но этого имени сейчас нет.
Нам нужно __приглашать__ к себе известные имена и компании. Я бы предложил более лояльный призыв с акцентом на использовании методологии: укажите свою компанию если "используете методологию", а не "если хотите быть в списке".

Хотите попасть в этот список?

---

README.md
website/i18n/en/docusaurus-plugin-content-docs/current/intro.md

- Поправил перевод в Intro Readme
- Сделал перевод доки одинаковым с readme

docs: align intro and readme translations

---

website/i18n/ru/docusaurus-plugin-content-docs/current/reference/layers/entities.md

импортируется BookCard, но используется Book, я так понимаю это просто была орфографическая ошибка, или тут был какой то сакральный смысл?

fix: component name

---

website/package.json
website/plugins/docusaurus-plugin-open-graph-image/config.js
website/plugins/docusaurus-plugin-open-graph-image/font.js
website/plugins/docusaurus-plugin-open-graph-image/image.js
website/plugins/docusaurus-plugin-open-graph-image/index.js
website/plugins/docusaurus-plugin-open-graph-image/layout.js
website/plugins/docusaurus-plugin-open-graph-image/template.js
website/plugins/docusaurus-plugin-open-graph-image/utils.js

Добавлено/изменено: 
- Теперь работа с файловой системой асинхронна.
- Путь к файлам теперь везде получается через path.resolve
- Добавлены логи работы плагина.
- Разукрашены логи для их большей заметности (т.к. логи ошибок пролетали обычным текстом)
https://github.com/feature-sliced/documentation/pull/368#pullrequestreview-829641938
#251 #375

PROMO-251(OG Plugin): Minor refinements (fs, logs)

---

.github/pull_request_template.md

- Removed the checklist from the template
- Removed CAPS from the Changelog heading
- Sprinkled in some emojis and lightened up the language
---
1. Removing CAPS from the Changelog
Looks calmer and more consistent with the other heading (even though I removed the other one)
2. Removing the sample list that says "Added smth, fixed smth"
It gets in the way because it has to be deleted/rewritten. The only benefit I see from it is to teach Markdown lists, but I don't think we should make effort towards that.  
**Proposed solution**: Mention in the comment that lists work best.
3. Removing the checklist
I moved all of the points of the checklist into other places which I believe to be more appropriate.
1. Contributing guidelines
Moved that into a P.S. comment because it is mostly useful to …

CONTRIB: Remove the checklist to make the PR template friendlier

---

i18n/en/docusaurus-plugin-content-docs/current/get-started/quick-start.md
i18n/en/docusaurus-plugin-content-docs/current/guides/examples/auth.mdx

Closes #481. Ran a case-insensitive search for `feature sliced` and `feature-sliced` and reviewed all results.
- Fixed all occurences of the brand name to the official "Feature-Sliced Design"
One of the fixes references this discussion — https://github.com/feature-sliced/documentation/discussions/65, which has an incorrect spelling in the name. We should fix that there as well, perhaps

PROMO-481: Correct the FSD spelling to the official one across all pages

---

i18n/en/docusaurus-plugin-content-docs/current/intro.mdx

Closes #440 
1. Added the "Is it right for me?" section, covering project size, tech stack and incremental adoption
2. Removed "the list" and moved part of it into the "Basics" section

feat(intro): add a "For Whom" section

---

i18n/en/docusaurus-plugin-content-docs/current/intro.mdx

Closes #441, closes #442, closes #444
1. Described the core concepts of the methodology
2. Added a decomposition example
3. Added a migration strategy (shared by @unordinarity in the Telegram chat)

feat(intro): finish the proposed corrections to the intro page

---

i18n/ru/docusaurus-plugin-content-docs/current/get-started/basics.md

In russian translation was typo on widgets in structure
Fixed typo in widgets

fix(basics): widget typo in structure

---

i18n/en/docusaurus-plugin-content-docs/current/privacy.md

removed not required -s(-es) endings
Removed unnecessary -s(-es) endings on privacy page
Removed unnecessary -s(-es) endings on privacy page

[privacy.md] grammar fixes

---

i18n/en/docusaurus-plugin-content-docs/current/reference/units/decomposition.md

Fix broken link, https://feature-sliced.design/docs/reference/units/layers/features#structural-grouping-features, does not redirect to the right part of article, but https://feature-sliced.design/docs/reference/units/layers/features#structural-grouping-of-features does.

Fix broken link documentation/decomposition.md

---

i18n/en/docusaurus-plugin-content-docs/current/get-started/tutorial.md
i18n/ru/docusaurus-plugin-content-docs/current/get-started/tutorial.md

Names collisions should be resolved at the level of public interface, not implementation. Here it exports directly FooCard, but it should export Card as FooCard, the same with FooThumbnail.
Source: https://feature-sliced.design/docs/reference/public-api#resolution-of-collisions

Fix name collisions documentation/tutorial.md

---

src/app/theme.scss

Closes #544 
Before (Chrome):
Before (Safari):
✅ After:

Fix: Added ubuntu-700 font-face

---

LICENSE
i18n/en/docusaurus-theme-classic/footer.json
i18n/ru/docusaurus-theme-classic/footer.json

2022 year in the footer of the docs website and in the LICENSE
updated current copyright and LICENSE year to 2023

chore(copyright): updated current copyright year

---

i18n/en/docusaurus-plugin-content-docs/current/reference/units/segments.md
i18n/ru/docusaurus-plugin-content-docs/current/reference/units/segments.md

* Add used import "Layout"
* Add final ;
* Add in the tree, the styles.module.scss file used in the examples below.
I think adding the styles.module.scss file in the tree helps understanding that inner modules use the styles defined at the start module.
Also the Layout import may help someone that does not understand where it comes from.

Update segment ui examples, in both en/ru

---

i18n/en/docusaurus-plugin-content-docs/current/reference/units/decomposition.md
i18n/ru/docusaurus-plugin-content-docs/current/reference/units/decomposition.md

Layers order section on [Decomposition page](https://feature-sliced.design/docs/reference/units/decomposition) lacks the `widgets` layer.
1. Added `widgets` to the English version of Decomposition page.
2. Added `widgets` to the Russian version of Decomposition page.

Add widgets to Layers order of Decomposition page

---

i18n/en/docusaurus-plugin-content-docs/current/reference/layers.mdx
i18n/ru/docusaurus-plugin-content-docs/current/reference/layers.mdx

The current version of the import rule on layers goes like this:
> A module can only import other modules when they are located on layers strictly below.
Nothing about the fact that imports inside the slice are allowed. That's no good.
1. Add more details to the rule so that it actually makes sense

fix: elaborate on the import rule on layers

---

config/docusaurus/routes.js

Our ESLint config links to a non-existent URL, no bueno
1. Redirect from `/reference/layers/overview` to `/reference/layers`

fix: add another missing redirect

---

config/docusaurus/footer.js
i18n/en/docusaurus-theme-classic/footer.json
i18n/ru/docusaurus-theme-classic/footer.json

The link to the "Discussions" section in GitHub in Footer was pointed with the "to" attribute as it's a path inside a router. That can cause some trouble in future versions. And also, because of this, the link was missing the external link icon
Also in the footer translations were missing items for the Help and Community links.
1. Changed link attribute to Discussions section in the Footer
2. Added translation items for Help and Community links.

fix: set correct attribute to Discussions section in footer, add translations

---

i18n/en/docusaurus-plugin-content-docs/current/get-started/tutorial.md
i18n/ru/docusaurus-plugin-content-docs/current/get-started/tutorial.md

Remove code block, which contained import of `antd/dist/antd.css`. The main reason why I do so - is that this approach doesn't actual at v5 of antd. 
For proving it, you can read [the list of incompatible changes in v5](https://ant.design/docs/react/migration-v5#incompatible-changes-in-v5) on official site, especially ["Technology adjustment" block](https://ant.design/docs/react/migration-v5#technology-adjustment)
> Css files are no longer included in package. Since CSS-in-JS supports importing on demand, the original `antd/dist/antd.css` has also been abandoned. If you need to reset some basic styles, please import `antd/dist/reset.css`.

docs: Remove code block, which contained import of common antd styles

---

i18n/en/docusaurus-plugin-content-docs/current/get-started/tutorial.md
i18n/ru/docusaurus-plugin-content-docs/current/get-started/tutorial.md

Update block codes at ["Let's form the routes" section](https://feature-sliced.design/ru/docs/get-started/tutorial#lets-form-the-routes), which allows us to see and use actual version and state of `react-router-dom` library.
Starting from v6 version,  `react-router-dom`  marked `Switch` and `Redirect` (that placed inside of `Switch`) as deprecated components. As a recomendation `Switch` should be replaced by `Routes`, and `Redirect` by `Navigate`.
* [Upgrade all `<Switch>` elements to `<Routes>`](https://reactrouter.com/en/main/upgrading/v5#upgrade-all-switch-elements-to-routes)
* [Advantages of `<Route element>`](https://reactrouter.com/en/main/upgrading/v5#advantages-of-route-element)
* [Remove `<Redirect>`s inside `<Switch>`](https://reactrouter.com/en/main/upgrading/v5#remove-redirects …

Docs: update block codes at "Let's form the routes" section

---

i18n/en/docusaurus-plugin-content-docs/current/get-started/faq.md
i18n/ru/docusaurus-plugin-content-docs/current/get-started/faq.md

The old FAQ had several issues:
1. It contained questions that are no longer being asked, for example, about FSD v1
2. It wasn't very accurately translated into English
3. It contained outdated information, for example, about linters and examples
4. It contained advice that I straight up disagree with, for example, about prohibiting putting feature code directly into pages when it makes sense.
Refreshed and rephrased the FAQ

feat: refresh the FAQ

---

config/docusaurus/extensions.js

It was disabled before, I don't know why. All I know is that search in other languages doesn't work and Algolia is such a complicated pile of junk that I'm reaching for anything.
I'm going by [this guide](https://docusaurus.io/docs/search#using-algolia-docsearch) and just resetting everything to defaults

feat: enable algolia contextual search

---

i18n/ru/docusaurus-plugin-content-docs/current/get-started/tutorial.md

Исправил ошибку в примере, путем приведения её к состоянию как в англоязычной версии туториала.
[EN] В англоязычной версии пример верен. 
https://github.com/feature-sliced/documentation/blob/629b61f06924d8186bb89b42f0a259424c0a76b9/i18n/en/docusaurus-plugin-content-docs/current/get-started/tutorial.md?plain=1#L289
[RU] В русскоязычном примере допущена ошибка в пути. 
https://github.com/feature-sliced/documentation/blob/629b61f06924d8186bb89b42f0a259424c0a76b9/i18n/ru/docusaurus-plugin-content-docs/current/get-started/tutorial.md?plain=1#L287

fix(docs-i18n-ru): fix typo in example

---

i18n/en/docusaurus-plugin-content-docs/current/get-started/tutorial.md
i18n/ru/docusaurus-plugin-content-docs/current/get-started/tutorial.md

Привет 👋
Correct: https://github.com/feature-sliced/tutorial-conduit/blob/main/shared/api/auth.server.ts#L51
No correct: [EN](https://github.com/feature-sliced/documentation/blob/master/i18n/en/docusaurus-plugin-content-docs/current/get-started/tutorial.md?plain=1#L830 ), [RU](https://github.com/feature-sliced/documentation/blob/master/i18n/ru/docusaurus-plugin-content-docs/current/get-started/tutorial.md?plain=1#L827)
**Мотивация:**
Строгое следование туториалу (код и структура приложения используется из примеров),  приводит приложение к крашу по завершению [этапа с созданием хедара приложения](https://feature-sliced.design/ru/docs/get-started/tutorial#%D1%85%D1%8D%D0%B4%D0%B5%D1%80).
**Причина:**
Проблема заключается в [предыдущем …

fix(docs-i18n-ru/en): fix crash on "header" stage in tutorial;

---

i18n/en/docusaurus-plugin-content-docs/current/get-started/tutorial.md
i18n/ru/docusaurus-plugin-content-docs/current/get-started/tutorial.md

Исправил внутри слоя `pages` название слайса `article-reader`, согласно объявленной структуре([ru](https://github.com/feature-sliced/documentation/blob/master/i18n/ru/docusaurus-plugin-content-docs/current/get-started/tutorial.md?plain=1#L34) / [en](https://github.com/feature-sliced/documentation/blob/master/i18n/en/docusaurus-plugin-content-docs/current/get-started/tutorial.md?plain=1#L33)) в начале туториала.
Опечатка:
[RU]: https://github.com/feature-sliced/documentation/blob/master/i18n/ru/docusaurus-plugin-content-docs/current/get-started/tutorial.md?plain=1#L1520-L1523
[EN]: https://github.com/feature-sliced/documentation/blob/master/i18n/en/docusaurus-plugin-content-docs/current/get-started/tutorial.md?plain=1#L1523-L1526

fix(docs-i18n-ru/en): typo in example

---

src/pages/examples/_config.ts

This pull request removes several outdated website links from the examples configuration file that were either no longer functioning or redundant due to redirections to the source URLs.
- Removed specific website entries that are obsolete or duplicate the source links provided in the configuration.
- Regarding vk audiopad, there was a link in the repository, so I used that and changed it to the website link.
The removal of these links simplifies the information presented in the examples, ensuring that users are not misdirected by inactive or redundant URLs.
If you find this pull request unnecessary, or if further modifications are required, please feel free to reject or suggest necessary revisions.
```
[INFO] [en] Creating an optimized production build...
✔ Client
Compiled successfully in …
```

Remove obsolete website links from example configurations

---

i18n/en/docusaurus-plugin-content-docs/current/guides/tech/with-react-query.mdx
i18n/ru/docusaurus-plugin-content-docs/current/guides/tech/with-react-query.mdx

This PR added example of usage React Query with FSD

feat: add react query example

---

i18n/en/docusaurus-plugin-content-docs/current/guides/tech/with-nuxtjs.mdx
i18n/ru/docusaurus-plugin-content-docs/current/guides/tech/with-nuxtjs.mdx

Добрый день!
Поправлен путь алиаса "@".
Если указывать \~, то в tsconfig при сборке указывается буквально "~/src". tsconfig не в курсе что за \~, а поэтому ide (в моём случае vs code) начинает колбасить при импортах.

fix: change alias path in the Nuxt guide

---

docusaurus.config.js
i18n/en/docusaurus-plugin-content-docs/current/guides/tech/with-nextjs.mdx
i18n/ru/docusaurus-plugin-content-docs/current/guides/tech/with-nextjs.mdx

As pointed out in the docs, it's not enough to simply have `app` in the root folder, you must also have `pages`. To ensure that the guide is working as expected, we will also provide a runnable link to a project.
1. Changed the file structure in the App Router example to include the `pages` folder in the root
2. Added a StackBlitz link with a Next.js project that implements this guide

fix: fix a section in the Next.js guide and add an example

---

i18n/en/docusaurus-plugin-content-docs/current/get-started/tutorial.md
i18n/ru/docusaurus-plugin-content-docs/current/get-started/tutorial.md

Someone left feedback that the markup in our tutorial code is slightly invalid
1. Move the `<p>` out of the `<ul>` tag list

fix: make the markup in the tutorial valid

---

src/entities/example/index.tsx
src/pages/examples/_config.ts

Hi everyone! I looked through all the examples in the documentation and found that some of the website links were broken, and some were in the repository but not listed in the documentation. I fixed that.
- MokeSmoke (add website)
- Sudoky Effector (remove website)

fix: add/remove website urls in examples

---

i18n/en/docusaurus-plugin-content-docs/current/guides/tech/with-nuxtjs.mdx
i18n/ru/docusaurus-plugin-content-docs/current/guides/tech/with-nuxtjs.mdx
src/entities/example/index.tsx
src/pages/examples/_config.ts

Added a guide to adding router config to nuxtjs project

feat: added config routing to nuxtjs guide

---

i18n/en/docusaurus-plugin-content-docs/current/guides/tech/with-nextjs.mdx

Closes #714 
1. Fix the typo that said "app" instead of "pages" in the Next.js guide (en)

fix: correct a layer name typo in the next guide

---

src/app/index.scss
src/features/feedback/doc/index.tsx
src/theme/DocItem/Footer/index.tsx

Someone left feedback saying that the current position of the feedback widget gets in the way of reading the docs on mobile. Let's try a different position.
1. Move the feedback bottom from center right to bottom right

Move the feedback button to the bottom

---

CHANGELOG.md
config/docusaurus/navbar.js
i18n/en/docusaurus-plugin-content-docs/current/guides/migration/from-v1.md
i18n/ru/docusaurus-plugin-content-docs/current/guides/migration/from-v1.md
src/features/hero/index.tsx
src/pages/versions/index.tsx

The `featureslices.dev` domain no longer works, so we can just link to GitHub
1. Replace all references to featureslices.dev with links to GitHub

Fix the broken featureslices.dev domain

---

i18n/kr/code.json
i18n/kr/docusaurus-plugin-content-docs/current/get-started/faq.md
i18n/kr/docusaurus-plugin-content-docs/current/get-started/tutorial.md

Translated the tutorial and FAQ pages to make it easier for Koreans to learn FSD.

feat: main, tutorial, and FAQ pages translated into Korean

---

i18n/kr/docusaurus-plugin-content-docs/current/guides/index.mdx

I have translated the Guide page into Korean. 

docs: guides page translated into Korean

---

i18n/en/docusaurus-plugin-content-docs/current/guides/tech/with-nuxtjs.mdx
i18n/en/docusaurus-plugin-content-docs/current/guides/tech/with-sveltekit.mdx
i18n/ru/docusaurus-plugin-content-docs/current/guides/tech/with-sveltekit.mdx

Someone pointed them out in PushFeedback:
> 1. "home-page.vue" should be "home-page.svelte" 
> 2. "Create a root" should be "Create a route" 
> 3. "index.svelte" should be "+page.svelte"
Fix the above typos and improve some phrasing a bit

fix: fix typos in the SvelteKit guides

---

i18n/kr/docusaurus-plugin-content-docs/current/guides/examples/index.mdx

I have translated the Guide page into Korean.

docs: guide example page translated into Korean

---

i18n/kr/docusaurus-plugin-content-docs/current/guides/examples/types.md

I have translated the examples Authentication page into Korean.

docs: types page translated into Korean

---

i18n/kr/docusaurus-plugin-content-docs/current/guides/tech/with-nextjs.mdx

We translated the Using with NextJS page.

docs: with-nextjs  page translated into Korean

---

i18n/kr/docusaurus-plugin-content-docs/community/index.mdx
i18n/kr/docusaurus-plugin-content-docs/community/team.mdx

We translated the Using with community page.

docs: community page translated into Korean

---

i18n/en/docusaurus-plugin-content-docs/current/guides/examples/types.md
i18n/ja/docusaurus-plugin-content-docs/current/guides/examples/types.md
i18n/kr/docusaurus-plugin-content-docs/current/guides/examples/types.md
i18n/ru/docusaurus-plugin-content-docs/current/guides/examples/types.md

Just fixes typo in code example by replacing usersAdapter to artistAdapter
Documentation page:
https://feature-sliced.design/docs/guides/examples/types#how-to-deal-with-nested-dtos
Here, usersAdapter is undefined and probably just wrong. So artistAdapter must be used

docs: change usersAdapter to artistAdapter

---

LICENSE
i18n/en/docusaurus-theme-classic/footer.json
i18n/ja/docusaurus-theme-classic/footer.json
i18n/ru/docusaurus-theme-classic/footer.json
i18n/uz/docusaurus-theme-classic/footer.json

I noticed several pages/translations have different copyright years.
I've crate PR which could help in 2025.

fix: update copyright year 2025 in advance

---

i18n/en/docusaurus-plugin-content-docs/current/guides/tech/with-nextjs.mdx

Noticed a small issue on the page - https://feature-sliced.design/docs/guides/tech/with-nextjs#app-router, where the `pages` layer is confused with `app` in the comments.
Adjusted comment on the page - replaced `FSD app folder` with `FSD pages folder` for `pages` layer

docs: fsd app replaced with fsd pages in en comments

---

i18n/kr/docusaurus-plugin-content-docs/current/guides/migration/from-v2-0.md

We translated the Using with migration from v2.0 to v2.1 page.

docs: migration from v2.0 to v2.1 page translated into Korean

---

i18n/kr/docusaurus-plugin-content-docs/current/guides/issues/_category_.yaml
i18n/kr/docusaurus-plugin-content-docs/current/guides/issues/cross-imports.mdx
i18n/kr/docusaurus-plugin-content-docs/current/guides/issues/desegmented.mdx
i18n/kr/docusaurus-plugin-content-docs/current/guides/issues/routes.mdx

We translated the cross-imports page, the desegmented page, and the routes page.

docs: translate code smells documentation pages into korean

---

i18n/kr/docusaurus-plugin-content-docs/current/guides/issues/cross-imports.mdx

Updated the guide title to use "Cross-import" instead of the Korean term for better clarity and understanding. The English term "Cross-import" is more widely recognized and better represents the technical concept being discussed.

docs: Update Korean title to English in Cross-imports guide

---

i18n/kr/docusaurus-plugin-content-docs/current/guides/tech/with-sveltekit.mdx

I translated the svelteKit page into Korean.

docs: svelteKit page translated into Korean

---

i18n/kr/docusaurus-plugin-content-docs/current/reference/slices-segments.mdx

I translated the `slices-segments` page into Korean.

docs: slices-segments page translated into Korean

---

i18n/kr/docusaurus-plugin-content-docs/current/reference/public-api.md

I translated the `Public API` page into Korean.

docs: Public API page translated into Korean

---

i18n/uz/docusaurus-plugin-content-docs/current/get-started/overview.mdx

This PR adds the Uzbek language translation for the overview page. I'm a new contributor, and I'm still learning, so there might be some mistakes in my changes. Please feel free to point them out!
There is no related issue for this change.
1. Added translation for the overview page to Uzbek language.

Add translation for overview page to Uzbek language

---

.github/workflows/deploy.yml
.github/workflows/testing.yml
CHANGELOG.md
CNAME
README.md
blog/2022-06-04-rebranding.md
blog/2022-07-25-international-community.md
config/docusaurus/consts.js
docusaurus.config.js
package.json
pnpm-lock.yaml
src/app/theme.scss
static/CNAME
static/robots.txt

Due to GoDaddy's shitty actions towards paying customers and their support not being empowered to fix a clear and easy problem, the `feature-sliced.design` domain that once brought me into this community is now lost. Maybe we will be able to recover it in the future, but it's not for certain.
The documentation is now hosted on the default domain of GitHub Pages, https://feature-sliced.github.io/documentation/

fix: replace the domain with the default GitHub one

---

i18n/en/docusaurus-plugin-content-docs/current/guides/tech/with-nextjs.mdx
i18n/ru/docusaurus-plugin-content-docs/current/guides/tech/with-nextjs.mdx

Updated the documentation for NextJS. Added an explanation about the need to place the `middleware` file in the root directory of the project.

docs: add middleware section to NextJS guide in English and Russian

---

i18n/en/docusaurus-plugin-content-docs/current/reference/public-api.md

Fixed a typo:  opporutnity -> opportunity.

Fixed: typo in public-api documentation

---

i18n/kr/docusaurus-plugin-content-docs/current/guides/tech/with-nextjs.mdx

The "Usage with NextJS" document has been updated.
- Improved clarity and readability in the translation:
- Standardized terminology (consistently using "폴더" instead of mixing "디렉토리" and "폴더")
- Overall, we have improved the sentences to be more understandable by using accurate terminology.

docs: Update Korean translation for 'Usage with NextJS' document

---

i18n/kr/docusaurus-plugin-content-docs/current/guides/tech/with-react-query.mdx

- Translate React Query related terms (query, mutation, etc.) to English
- Unify Feature-Sliced Design architecture terminology in English
Reverted React Query terminology from Korean to original English to prevent meaning distortion and maintain technical accuracy. English terms provide better clarity and consistency with official documentation.

docs: standardize English terminology in with-react-query documentation

---

i18n/kr/docusaurus-plugin-content-docs/current/guides/examples/types.md

A complete rewrite of the Korean **Type Guide** documentation.
- Replaces ambiguous or literal‑translation terms with standard dev vocabulary.  
- Streamlines long sentences and re‑orders sections for faster lookup.  
- issue fix #819
- Added **Business entity & mutual references** section.  
- Merged DTO/mapper and Zod validation notes under `api / ui` segments.  
- Consolidated Global types, Ambient declarations into one chapter.
- Mixed translated terms confused new contributors.  
- Layer rules were scattered, slowing onboarding.  
- Examples used outdated folder names not matching the current repo.

docs(ko): rewrite of Korean Type Guide — terminology cleanup & structural overhaul

---

i18n/kr/docusaurus-plugin-content-docs/current/get-started/faq.md

The Korean FAQ page was wordy, contained meta‑phrases, and repeated ideas.  
Using our style checklist (concise sentences, no meta‑talk, clear subject, consistent terms), I rewrote the answers to read faster and added minor structural tweaks (info box, table, bullet lists).
- Rephrased all Q&A for brevity and active voice.
- Added a comparison table for **Feature vs Entity**.

docs(ko): refine FAQ page for brevity & clarity

---

i18n/kr/docusaurus-plugin-content-docs/current/get-started/index.mdx

To keep the Korean docs fully localised, we changed the page header from “Get Started” to **“시작하기”** and rewrote the summary / NavCard descriptions for clearer, action‑oriented wording.  
Action‑verbs (“살펴봅니다”, “적용해 봅니다”, “해결합니다”) guide readers toward the next step and improve scan‑ability, especially for first‑time visitors.
- Rename page heading: `# 🚀 Get Started` → `# 🚀 시작하기`.
- Rephrased summary paragraph (shorter, highlights benefits and background).
- Updated NavCard descriptions:
- Overview – “FSD’s concept, structure, usage at a glance.”
- Tutorial – “Hands‑on steps to apply FSD.”
- FAQ – “Answers to common questions.”
-

docs(ko): rename “Get Started” → “시작하기” and polish nav‑card texts

---

i18n/kr/docusaurus-plugin-content-docs/current/guides/examples/page-layout.md

Concisely restructured the intro to clearly distinguish the shared overall layout (header, sidebar, footer) from the page-specific main content, making the page layout concept easy to understand.
Detailed why placing the layout component in shared/widgets violates the FSD layer import rule by outlining the dependency flow step by step.
Refined the “Inline layout in the App layer” and “Copy & paste” suggestions with clear examples and concise wording, offering pragmatic solutions that minimize abstraction and reduce the scope of changes.

docs(ko): rewrite of Korean page-layout Guide — sentence structure check

---

i18n/kr/docusaurus-plugin-content-docs/current/guides/examples/api-requests.mdx
i18n/kr/docusaurus-plugin-content-docs/current/guides/examples/index.mdx
i18n/kr/docusaurus-plugin-content-docs/current/guides/examples/types.md

- Translated the `Shared API Requests` section into Korean.
- Translated the `Slice-specific API Requests` section into Korean.
- Translated the `API Types & Client Generators` section into Korean.
- Translated the `Integrating with Server State Libraries` section into Korean.
- Changed page summary from "방법론 적용에 대한 예시들" to "FSD Architecture 적용 사례" because the term “methodology” was confusing.
- Unified NavCard titles to English ("Authentication", "Types", "Page layouts") for better readability.
- Imported ApiOutlined icon and added a new NavCard for "API Requests" with description "공통 및 Slice-specific API Requests 관리".

docs(ko): translate API Requests guide to Korean

---

docusaurus.config.js

- A Prettier formatting issue was detected in `docusaurus.config.js`, so the file’s code style was updated.

chore: fix prettier formatting issues

---

i18n/kr/docusaurus-plugin-content-docs/current/reference/index.mdx
i18n/kr/docusaurus-plugin-content-docs/current/reference/layers.mdx
i18n/kr/docusaurus-plugin-content-docs/current/reference/public-api.md
i18n/kr/docusaurus-plugin-content-docs/current/reference/slices-segments.mdx

In this PR, I thoroughly revised the Korean translation of the official FSD documentation, focusing on the Layers, Slices & Segments, Public API, and Reference pages.
Rather than providing a direct translation, I refined the content to improve readability and clarity, ensuring that frontend developers can quickly and intuitively understand the concepts.

docs(ko): refine reference for improved readability

---

config/docusaurus/sidebars.docs.js

Previously, the docs had separate sidebars per section (Get started, Guides, Reference, About). While reading a page, you couldn’t see or jump to content from other sections without first navigating back to the docs landing and selecting the new section (2 clicks). This fragmented the global structure and made cross‑section navigation harder.
This PR unifies the docs navigation into a single sidebar that is always visible on every docs page. It improves discoverability and reduces navigation to a single click, without changing any URLs or document slugs.
1. Replace multiple per‑section sidebars with a single global docsSidebar composed of autogenerated categories.
2. Make the full documentation structure always visible in the left sidebar.
3. Enable one‑click switching between sections …

docs(sidebar): unify docs sidebar across sections
